// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://udqtihwsmcimmmnqwfqs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkcXRpaHdzbWNpbW1tbnF3ZnFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNzkzOTgsImV4cCI6MjA2MDk1NTM5OH0.wmlMvcmdOa2nT0ENMzsLskfz-zUP5ARni-SIQ_D6gTU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);